---
- name: install packages
  hosts: all
  become: true
  gather_facts: yes
  
  tasks:
  - name: install htpd on redhat
    yum:
             name: httpd
             state: installed
    notify: start httpd service

  - copy:
                  src: /home/ansadmin/playbooks/index.html
                  dest: /var/www/html

  handlers:
  - name: start httpd service
    service:
                name: httpd
                state: started
   


