---
- name: uninstall multiple packages
  hosts: all
  become: true
  gather_facts: true

  tasks:
      - name: remove httpd packages
        yum:
            name: httpd
            state: absent
        when: ansible_os_family == "RedHat"

