---
- name: playbook of install apache tomcat
  hosts: redhat
  become: true
  gather_facts: yes

  tasks:
          - name: install java-1.8*
            yum:
                  name: java
                  state: installed

          - name: download tomcat pkg
            get_url:
                  url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.53/bin/apache-tomcat-9.0.53.tar.gz
                  dest: /opt
                  mode: 0755

          - name: extract pkg
            unarchive:
                    src: /opt/apache-tomcat-9.0.53.tar.gz
                    dest: /opt
                    remote_src: yes

          - name: change permission on tomcat file
            file:
                    path: /opt/apache-tomcat-9.0.53
                    mode: 0755
                    recurse: yes

          - name: creating link file for tomcat startup.sh
            file:
                src: /opt/apache-tomcat-9.0.53/bin/startup.sh 
                dest: /usr/local/bin/tomcatup
                state: link

          - name: creating link for tomcat shutdown.sh file
            file:
                    src: /opt/apache-tomcat-9.0.53/bin/shutdown.sh
                    dest: /usr/local/bin/tomcatdown
                    state: link
          - name: start the tomcat services
            command: nohup ./startup.sh
            args:
                    chdir: /opt/apache-tomcat-9.0.53/bin
