---
- name: creating user
  hosts: all
  gather_facts: no
  become: true
  #  vars:
  #       user_name: modi
  vars_files:
          - /home/ansadmin/playbooks/users.yml
  tasks: 
        - name: create user {{ user_name }}
          user: 
                name: "{{ user_name }}"

        - name: create a directory
          file: 
                path: /opy/{{ user_name }}_temp_dir
                state: directory
                owner: "{{ user_name }}"
                group: "{{ user_name }}"
                mode: 0755
