---
- name: install packages
  hosts: all
  become: true
  gather_facts: yes
  
  tasks:
  - name: install htpd on redhat
    yum:
             name: httpd
             state: installed
    when: ansible_os_family == "RedHat"

  - name: install htpd on ubuntu
    apt:
                name: apache2
                state: present
    when: ansible_os_family == "Debian"

  - name: start apache service on ubuntu
    service:
                name: apache2
                state: started
    when: ansible_os_family == "Debian"

  - name: starting httpd
    service:
                name: httpd
                state: started
    when: ansible_os_family == "RedHat"

  - copy:
                  src: /home/ansadmin/playbooks/index.html
                  dest: /var/www/html

